# fly.toml app configuration file generated for cold-wildflower-1929 on 2023-07-27T13:35:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-wildflower-1929"
primary_region = "arn"
kill_signal = "SIGTERM"
swap_size_mb = 512

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "cold-wildflower-1929.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
